name: Hackathon Hunter

on:
  schedule:
    - cron: '0 */6 * * *'  # Har 6 ghante mein chalega
  workflow_dispatch:      # Button dabane par bhi chalega

permissions:
  contents: write  # Database file save karne ki permission

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Python Setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Libraries
      run: pip install -r requirements.txt

    - name: Run Crawler
      env:  # <--- YE LINE SABSE ZAROORI HAI
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: python main.py

    - name: Save Memory (Seen Hacks)
      run: |
        git config --global user.name 'HackathonBot'
        git config --global user.email 'bot@noreply.github.com'
        git add seen_hacks.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update DB" && git push)